/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and obtain JWT */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all servers with GPU summary */
        get: operations["listServers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a new resource application */
        post: operations["createApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my applications (paginated) */
        get: operations["listMyApplications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ErrorCode: "INVALID_ARGUMENT" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "STATE_CONFLICT" | "RATE_LIMITED" | "UPSTREAM_NETBIRD_ERROR";
        /** @enum {string} */
        AuditStatus: "APPROVED" | "ACTIVE" | "EXPIRED" | "FAILED_GRANT" | "FAILED_REVOKE";
        /** @enum {string} */
        ServerStatus: "ONLINE" | "OFFLINE" | "MAINTENANCE";
        /**
         * @description GPU tier enum used when creating applications
         * @enum {string}
         */
        ResourceLevel: "H100" | "A100" | "L40S" | "L4" | "T4";
        ErrorEnvelope: {
            code: components["schemas"]["ErrorCode"];
            message: string;
            data?: unknown;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        AuthResponse: {
            /** @description JWT access token */
            token: string;
            /** Format: email */
            email: string;
            roles: string[];
        };
        AuthResponseEnvelope: {
            /**
             * @description Empty string on success
             * @example
             */
            code: string;
            /** @example ok */
            message: string;
            data: components["schemas"]["AuthResponse"];
        };
        /** @description Submit application for a specific GPU server (Jackson camelCase). */
        CreateApplicationRequest: {
            /** @description Target server id from GET /api/servers */
            serverId: string;
            purpose: string;
            requestedDays: number;
            /** Format: date-time */
            requestedStartAt: string;
            /** @description Optional SSH password for the granted account */
            sshPassword?: string;
        };
        /** @description Application record; SSH fields appear when auditStatus is ACTIVE. */
        ApplicationVO: {
            id?: string;
            serverId?: string;
            resourceLevel?: string;
            purpose?: string;
            requestedDays?: number;
            /** Format: date-time */
            requestedStartAt?: string;
            /** Format: date-time */
            expireAt?: string | null;
            auditStatus?: components["schemas"]["AuditStatus"];
            comment?: string | null;
            /** @description Shown in UI when ACTIVE */
            serverIp?: string;
            sshUsername?: string;
            initialPassword?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApplicationResponseEnvelope: {
            /** @example  */
            code: string;
            /** @example ok */
            message: string;
            data: components["schemas"]["ApplicationVO"];
        };
        PageResultApplication: {
            items?: components["schemas"]["ApplicationVO"][];
            /** Format: int64 */
            total?: number;
            page?: number;
            pageSize?: number;
        };
        PageResultApplicationEnvelope: {
            /** @example  */
            code: string;
            /** @example ok */
            message: string;
            data: components["schemas"]["PageResultApplication"];
        };
        GpuSummaryBlock: {
            gpuCount?: number;
            /**
             * Format: double
             * @description Average GPU utilization, 0~1
             */
            avgUtil?: number;
            avgMemUsedMb?: number;
        };
        GpuRow: {
            index?: number;
            name?: string;
            /**
             * Format: double
             * @description 0~1
             */
            avgUtil?: number;
            memUsedMb?: number;
            memTotalMb?: number;
        };
        /** @description Public server row with stable id and GPU metrics. */
        ServerVO: {
            /** @description Stable server id used when submitting applications */
            id?: string;
            resourceLevel?: string;
            status?: components["schemas"]["ServerStatus"];
            /** Format: date-time */
            lastReportedAt?: string | null;
            /** Format: date-time */
            collectedAt?: string | null;
            summary?: components["schemas"]["GpuSummaryBlock"];
            gpus?: components["schemas"]["GpuRow"][];
        };
        ServerListData: {
            items?: components["schemas"]["ServerVO"][];
        };
        ServerListEnvelope: {
            /** @example  */
            code: string;
            /** @example ok */
            message: string;
            data: components["schemas"]["ServerListData"];
        };
    };
    responses: {
        /** @description Invalid argument or validation failure */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "INVALID_ARGUMENT",
                 *       "message": "email: must not be blank",
                 *       "data": null
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Not authenticated or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "UNAUTHORIZED",
                 *       "message": "Not authenticated",
                 *       "data": null
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Insufficient permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "FORBIDDEN",
                 *       "message": "权限不足",
                 *       "data": null
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOT_FOUND",
                 *       "message": "资源不存在或已变更",
                 *       "data": null
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description State conflict (e.g. duplicate registration) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "STATE_CONFLICT",
                 *       "message": "状态已变更，请刷新后重试",
                 *       "data": null
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Rate limited */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "RATE_LIMITED",
                 *       "message": "请求过于频繁，请稍后再试",
                 *       "data": null
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Upstream NetBird or dependency error */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "UPSTREAM_NETBIRD_ERROR",
                 *       "message": "上游服务暂时不可用，请稍后重试",
                 *       "data": null
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "",
                     *       "message": "ok",
                     *       "data": {
                     *         "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlbW9AZXhhbXBsZS5jb20iLCJyb2xlcyI6W119.mock",
                     *         "email": "demo@example.com",
                     *         "roles": []
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["AuthResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registration successful */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "",
                     *       "message": "ok",
                     *       "data": {
                     *         "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlbW9AZXhhbXBsZS5jb20iLCJyb2xlcyI6W119.mock",
                     *         "email": "demo@example.com",
                     *         "roles": []
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["AuthResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    listServers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "",
                     *       "message": "ok",
                     *       "data": {
                     *         "items": [
                     *           {
                     *             "id": "gpu-mock-001",
                     *             "resourceLevel": "H100",
                     *             "status": "ONLINE",
                     *             "lastReportedAt": "2026-05-18T08:00:00Z",
                     *             "collectedAt": "2026-05-18T08:00:00Z",
                     *             "summary": {
                     *               "gpuCount": 8,
                     *               "avgUtil": 0.42,
                     *               "avgMemUsedMb": 32768
                     *             },
                     *             "gpus": [
                     *               {
                     *                 "index": 0,
                     *                 "name": "NVIDIA H100",
                     *                 "avgUtil": 0.35,
                     *                 "memUsedMb": 40960,
                     *                 "memTotalMb": 81920
                     *               }
                     *             ]
                     *           }
                     *         ]
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ServerListEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["BadGateway"];
        };
    };
    createApplication: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID for idempotent submission; the frontend sends a fresh value on each submit. */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "serverId": "gpu-mock-001",
                 *       "purpose": "大模型预训练",
                 *       "requestedDays": 7,
                 *       "requestedStartAt": "2026-05-19T00:00:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["CreateApplicationRequest"];
            };
        };
        responses: {
            /** @description Application created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "",
                     *       "message": "ok",
                     *       "data": {
                     *         "id": "app-mock001",
                     *         "serverId": "gpu-mock-001",
                     *         "resourceLevel": "H100",
                     *         "purpose": "联调",
                     *         "requestedDays": 7,
                     *         "requestedStartAt": "2026-05-19T00:00:00Z",
                     *         "expireAt": "2026-05-26T00:00:00Z",
                     *         "auditStatus": "APPROVED",
                     *         "comment": null,
                     *         "createdAt": "2026-05-18T08:00:00Z",
                     *         "updatedAt": "2026-05-18T08:00:00Z"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ApplicationResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            502: components["responses"]["BadGateway"];
        };
    };
    listMyApplications: {
        parameters: {
            query?: {
                /** @description Filter by audit status */
                status?: components["schemas"]["AuditStatus"];
                /** @description Page number (1-based) */
                page?: number;
                /** @description Page size (max 100) */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated application list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "",
                     *       "message": "ok",
                     *       "data": {
                     *         "items": [
                     *           {
                     *             "id": "app-mock001",
                     *             "serverId": "1",
                     *             "resourceLevel": "H100",
                     *             "purpose": "联调",
                     *             "requestedDays": 7,
                     *             "requestedStartAt": "2026-05-19T00:00:00Z",
                     *             "expireAt": "2026-05-26T00:00:00Z",
                     *             "auditStatus": "ACTIVE",
                     *             "comment": null,
                     *             "serverIp": "10.0.0.101",
                     *             "sshUsername": "ubuntu",
                     *             "initialPassword": "ApifoxMock-Demo",
                     *             "createdAt": "2026-05-18T08:00:00Z",
                     *             "updatedAt": "2026-05-18T08:00:00Z"
                     *           }
                     *         ],
                     *         "total": 1,
                     *         "page": 1,
                     *         "pageSize": 20
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["PageResultApplicationEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
}
