/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and obtain JWT */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users (paginated, admin only) */
        get: operations["listAdminUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete user (admin only) */
        delete: operations["deleteAdminUser"];
        options?: never;
        head?: never;
        /** Update user (admin only) */
        patch: operations["updateAdminUser"];
        trace?: never;
    };
    "/api/admin/users/bulk-disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk disable users (admin only) */
        post: operations["bulkDisableUsers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/bulk-enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk enable users (admin only) */
        post: operations["bulkEnableUsers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/bulk-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk delete users (admin only) */
        post: operations["bulkDeleteUsers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import users from CSV (admin only) */
        post: operations["importUsers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all servers with GPU summary */
        get: operations["listServers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a new resource application */
        post: operations["createApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke or cancel my application */
        delete: operations["revokeApplication"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my applications (paginated) */
        get: operations["listMyApplications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ErrorCode: "INVALID_ARGUMENT" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "STATE_CONFLICT" | "RATE_LIMITED" | "UPSTREAM_NETBIRD_ERROR";
        /** @enum {string} */
        AuditStatus: "APPROVED" | "ACTIVE" | "REVOKING" | "REVOKED" | "CANCELLED" | "FAILED_GRANT" | "FAILED_REVOKE";
        /** @enum {string} */
        ServerStatus: "ONLINE" | "OFFLINE" | "MAINTENANCE";
        /**
         * @description GPU tier enum used when creating applications
         * @enum {string}
         */
        ResourceLevel: "H100" | "A100" | "L40S" | "L4" | "T4";
        ErrorEnvelope: {
            code: components["schemas"]["ErrorCode"];
            message: string;
            data?: unknown;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        UserImportError: {
            row: number;
            reason: string;
        };
        UserImportPassword: {
            /** Format: email */
            email: string;
            initialPassword: string;
        };
        UserImportResponse: {
            created: number;
            skipped: number;
            errors: components["schemas"]["UserImportError"][];
            passwords: components["schemas"]["UserImportPassword"][];
        };
        UserImportResponseEnvelope: {
            /** @example  */
            code: string;
            /** @example ok */
            message: string;
            data: components["schemas"]["UserImportResponse"];
        };
        /** @enum {string} */
        UserStatus: "ACTIVE" | "INACTIVE";
        AdminUserVO: {
            /** Format: int64 */
            id?: number;
            /** Format: email */
            email?: string;
            linuxUsername?: string;
            status?: components["schemas"]["UserStatus"];
            cohort?: string | null;
            displayName?: string | null;
            studentId?: string | null;
            notes?: string | null;
            label?: string | null;
            /** Format: int64 */
            activeAccessCount?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AdminUserEnvelope: {
            /** @example  */
            code: string;
            /** @example ok */
            message: string;
            data: components["schemas"]["AdminUserVO"];
        };
        UpdateAdminUserRequest: {
            displayName?: string | null;
            cohort?: string | null;
            notes?: string | null;
            label?: string | null;
            status?: components["schemas"]["UserStatus"];
        };
        PageResultAdminUser: {
            items?: components["schemas"]["AdminUserVO"][];
            /** Format: int64 */
            total?: number;
            page?: number;
            pageSize?: number;
        };
        PageResultAdminUserEnvelope: {
            /** @example  */
            code: string;
            /** @example ok */
            message: string;
            data: components["schemas"]["PageResultAdminUser"];
        };
        DeleteAdminUserResponse: {
            deleted?: boolean;
            pendingRevokes?: number;
            message?: string;
        };
        DeleteAdminUserResponseEnvelope: {
            /** @example STATE_CONFLICT */
            code: string;
            message: string;
            data: components["schemas"]["DeleteAdminUserResponse"];
        };
        BulkUserActionRequest: {
            ids?: number[];
            selectAll?: boolean;
            cohort?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE" | "all";
        };
        BulkDeleteUsersRequest: {
            ids?: number[];
            selectAll?: boolean;
            cohort?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE" | "all";
            /** @default false */
            revokeSsh: boolean;
        };
        BulkUserError: {
            /** Format: int64 */
            userId?: number;
            /** Format: email */
            email?: string;
            reason?: string;
        };
        BulkDisableUsersResponse: {
            disabled?: number;
            skipped?: number;
            errors?: components["schemas"]["BulkUserError"][];
        };
        BulkDisableUsersResponseEnvelope: {
            /** @example  */
            code: string;
            /** @example ok */
            message: string;
            data: components["schemas"]["BulkDisableUsersResponse"];
        };
        BulkEnableUsersResponse: {
            enabled?: number;
            skipped?: number;
            errors?: components["schemas"]["BulkUserError"][];
        };
        BulkEnableUsersResponseEnvelope: {
            /** @example  */
            code: string;
            /** @example ok */
            message: string;
            data: components["schemas"]["BulkEnableUsersResponse"];
        };
        BulkDeleteUsersResponse: {
            deleted?: number;
            pending?: number;
            skipped?: number;
            errors?: components["schemas"]["BulkUserError"][];
        };
        BulkDeleteUsersResponseEnvelope: {
            /** @example  */
            code: string;
            /** @example ok */
            message: string;
            data: components["schemas"]["BulkDeleteUsersResponse"];
        };
        AuthResponse: {
            /** @description JWT access token */
            token: string;
            /** Format: email */
            email: string;
            roles: string[];
        };
        AuthResponseEnvelope: {
            /**
             * @description Empty string on success
             * @example
             */
            code: string;
            /** @example ok */
            message: string;
            data: components["schemas"]["AuthResponse"];
        };
        /** @description Submit application for a specific GPU server (Jackson camelCase). */
        CreateApplicationRequest: {
            /** @description Target server id from GET /api/servers */
            serverId: string;
            /** @description Optional SSH password for the granted account */
            sshPassword?: string;
        };
        /** @description Application record; SSH fields appear when auditStatus is ACTIVE. */
        ApplicationVO: {
            id?: string;
            serverId?: string;
            resourceLevel?: string;
            auditStatus?: components["schemas"]["AuditStatus"];
            comment?: string | null;
            /** @description Shown in UI when ACTIVE */
            serverIp?: string;
            sshUsername?: string;
            initialPassword?: string;
            credentialsReady?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApplicationResponseEnvelope: {
            /** @example  */
            code: string;
            /** @example ok */
            message: string;
            data: components["schemas"]["ApplicationVO"];
        };
        PageResultApplication: {
            items?: components["schemas"]["ApplicationVO"][];
            /** Format: int64 */
            total?: number;
            page?: number;
            pageSize?: number;
        };
        PageResultApplicationEnvelope: {
            /** @example  */
            code: string;
            /** @example ok */
            message: string;
            data: components["schemas"]["PageResultApplication"];
        };
        GpuSummaryBlock: {
            gpuCount?: number;
            /**
             * Format: double
             * @description Average GPU utilization, 0~1
             */
            avgUtil?: number;
            avgMemUsedMb?: number;
        };
        GpuRow: {
            index?: number;
            name?: string;
            /**
             * Format: double
             * @description 0~1
             */
            avgUtil?: number;
            memUsedMb?: number;
            memTotalMb?: number;
        };
        /** @description Public server row with stable id and GPU metrics. */
        ServerVO: {
            /** @description Stable server id used when submitting applications */
            id?: string;
            resourceLevel?: string;
            status?: components["schemas"]["ServerStatus"];
            /** Format: date-time */
            lastReportedAt?: string | null;
            /** Format: date-time */
            collectedAt?: string | null;
            summary?: components["schemas"]["GpuSummaryBlock"];
            gpus?: components["schemas"]["GpuRow"][];
        };
        ServerListData: {
            items?: components["schemas"]["ServerVO"][];
        };
        ServerListEnvelope: {
            /** @example  */
            code: string;
            /** @example ok */
            message: string;
            data: components["schemas"]["ServerListData"];
        };
    };
    responses: {
        /** @description Invalid argument or validation failure */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "INVALID_ARGUMENT",
                 *       "message": "email: must not be blank",
                 *       "data": null
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Not authenticated or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "UNAUTHORIZED",
                 *       "message": "Not authenticated",
                 *       "data": null
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Insufficient permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "FORBIDDEN",
                 *       "message": "权限不足",
                 *       "data": null
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOT_FOUND",
                 *       "message": "资源不存在或已变更",
                 *       "data": null
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description State conflict (e.g. duplicate registration) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "STATE_CONFLICT",
                 *       "message": "状态已变更，请刷新后重试",
                 *       "data": null
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Rate limited */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "RATE_LIMITED",
                 *       "message": "请求过于频繁，请稍后再试",
                 *       "data": null
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Upstream NetBird or dependency error */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "UPSTREAM_NETBIRD_ERROR",
                 *       "message": "上游服务暂时不可用，请稍后重试",
                 *       "data": null
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "",
                     *       "message": "ok",
                     *       "data": {
                     *         "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlbW9AZXhhbXBsZS5jb20iLCJyb2xlcyI6W119.mock",
                     *         "email": "demo@example.com",
                     *         "roles": []
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["AuthResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAdminUsers: {
        parameters: {
            query?: {
                cohort?: string;
                status?: "ACTIVE" | "INACTIVE" | "all";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated user list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResultAdminUserEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    deleteAdminUser: {
        parameters: {
            query?: {
                /** @description When true, revoke SSH/GPU access before delete; may return 409 if revokes are pending */
                revokeSsh?: boolean;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Revoke in progress; retry delete later */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteAdminUserResponseEnvelope"];
                };
            };
        };
    };
    updateAdminUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAdminUserRequest"];
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    bulkDisableUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkUserActionRequest"];
            };
        };
        responses: {
            /** @description Bulk disable result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkDisableUsersResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    bulkEnableUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkUserActionRequest"];
            };
        };
        responses: {
            /** @description Bulk enable result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkEnableUsersResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    bulkDeleteUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkDeleteUsersRequest"];
            };
        };
        responses: {
            /** @description Bulk delete result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkDeleteUsersResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    importUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description CSV with columns: email,linux_username,display_name,student_id,cohort,initial_password,roles
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Import result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserImportResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listServers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "",
                     *       "message": "ok",
                     *       "data": {
                     *         "items": [
                     *           {
                     *             "id": "gpu-mock-001",
                     *             "resourceLevel": "H100",
                     *             "status": "ONLINE",
                     *             "lastReportedAt": "2026-05-18T08:00:00Z",
                     *             "collectedAt": "2026-05-18T08:00:00Z",
                     *             "summary": {
                     *               "gpuCount": 8,
                     *               "avgUtil": 0.42,
                     *               "avgMemUsedMb": 32768
                     *             },
                     *             "gpus": [
                     *               {
                     *                 "index": 0,
                     *                 "name": "NVIDIA H100",
                     *                 "avgUtil": 0.35,
                     *                 "memUsedMb": 40960,
                     *                 "memTotalMb": 81920
                     *               }
                     *             ]
                     *           }
                     *         ]
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ServerListEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["BadGateway"];
        };
    };
    createApplication: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID for idempotent submission; the frontend sends a fresh value on each submit. */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "serverId": "gpu-mock-001"
                 *     }
                 */
                "application/json": components["schemas"]["CreateApplicationRequest"];
            };
        };
        responses: {
            /** @description Application created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "",
                     *       "message": "ok",
                     *       "data": {
                     *         "id": "app-mock001",
                     *         "serverId": "gpu-mock-001",
                     *         "resourceLevel": "H100",
                     *         "auditStatus": "APPROVED",
                     *         "comment": null,
                     *         "credentialsReady": false,
                     *         "createdAt": "2026-05-18T08:00:00Z",
                     *         "updatedAt": "2026-05-18T08:00:00Z"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ApplicationResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            502: components["responses"]["BadGateway"];
        };
    };
    revokeApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application revoked or cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "",
                     *       "message": "ok",
                     *       "data": {
                     *         "id": "app-mock001",
                     *         "serverId": "gpu-mock-001",
                     *         "resourceLevel": "H100",
                     *         "auditStatus": "REVOKING",
                     *         "comment": null,
                     *         "credentialsReady": false,
                     *         "createdAt": "2026-05-18T08:00:00Z",
                     *         "updatedAt": "2026-05-18T09:00:00Z"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ApplicationResponseEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listMyApplications: {
        parameters: {
            query?: {
                /** @description Filter by audit status */
                status?: components["schemas"]["AuditStatus"];
                /** @description Page number (1-based) */
                page?: number;
                /** @description Page size (max 100) */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated application list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "",
                     *       "message": "ok",
                     *       "data": {
                     *         "items": [
                     *           {
                     *             "id": "app-mock001",
                     *             "serverId": "1",
                     *             "resourceLevel": "H100",
                     *             "auditStatus": "ACTIVE",
                     *             "comment": null,
                     *             "serverIp": "10.0.0.101",
                     *             "sshUsername": "ubuntu",
                     *             "initialPassword": "ApifoxMock-Demo",
                     *             "credentialsReady": true,
                     *             "createdAt": "2026-05-18T08:00:00Z",
                     *             "updatedAt": "2026-05-18T08:00:00Z"
                     *           }
                     *         ],
                     *         "total": 1,
                     *         "page": 1,
                     *         "pageSize": 20
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["PageResultApplicationEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
}
